apiVersion: apps/v1
kind: Deployment
metadata:
    name: python-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: python-service
    template:
        metadata:
            labels:
                app: python-service
        spec:
            containers:
                - name: python-service
                  image: vincent7891/python-service:latest
                  ports:
                      - containerPort: 8080
