apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-service
spec:
    replicas: 5
    selector:
        matchLabels:
            app: go-service
    template:
        metadata:
            labels:
                app: go-service
        spec:
            containers:
                - name: go-service
                  image: vincent7891/go-service:latest
                  ports:
                      - containerPort: 8080
